---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cbtsmpam/qrhadir.my.id
    - /bin/rsync -av --delete \
      --exclude='.git' \
      --exclude='.env' \
      --exclude='storage' \
      --exclude='vendor' \
      ./ $DEPLOYPATH/